"""add first_name and last_name to dialog

Revision ID: 2006abdd7c66
Revises: 3d08709f8f54
Create Date: 2025-06-18 15:17:49.732452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2006abdd7c66'
down_revision: Union[str, Sequence[str], None] = '3d08709f8f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('dialogs', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'last_name')
    op.drop_column('dialogs', 'first_name')
    # ### end Alembic commands ###
