"""Add webhook_processed_at field to payments table for security

Revision ID: 21bcb2d9691c
Revises: d365d57efcba
Create Date: 2025-09-10 22:11:25.375155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bcb2d9691c'
down_revision: Union[str, Sequence[str], None] = 'd365d57efcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('webhook_processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'webhook_processed_at')
    # ### end Alembic commands ###
