"""add email confirmation fields to user

Revision ID: 24c3adfca86c
Revises: 3cc45be8d398
Create Date: 2025-06-18 16:45:59.310821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c3adfca86c'
down_revision: Union[str, Sequence[str], None] = '3cc45be8d398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmation_code')
    op.drop_column('users', 'is_email_confirmed')
    # ### end Alembic commands ###
