"""add yandex_id to user

Revision ID: 3cc45be8d398
Revises: 217ce33d5f67
Create Date: 2025-06-18 16:04:53.107353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc45be8d398'
down_revision: Union[str, Sequence[str], None] = '217ce33d5f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['yandex_id'])
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
