"""add broadcast_reads table

Revision ID: 3d08709f8f54
Revises: 5b2babd8ae17
Create Date: 2025-06-18 13:05:40.567770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d08709f8f54'
down_revision: Union[str, Sequence[str], None] = '5b2babd8ae17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['dialog_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast_reads')
    # ### end Alembic commands ###
