"""Add YooKassa fields to Payment model

Revision ID: 85e1ab744cb0
Revises: 21bcb2d9691c
Create Date: 2025-09-12 12:23:38.691779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e1ab744cb0'
down_revision: Union[str, Sequence[str], None] = '21bcb2d9691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('yookassa_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('yookassa_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'yookassa_status')
    op.drop_column('payments', 'yookassa_payment_id')
    # ### end Alembic commands ###
