"""add_blog_scheduling_fields

Revision ID: c87bcb311c52
Revises: 84035cb4ffc2
Create Date: 2025-09-20 13:52:30.107246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87bcb311c52'
down_revision: Union[str, Sequence[str], None] = '84035cb4ffc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('blog_posts', sa.Column('initial_views', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('initial_likes', sa.Integer(), nullable=True))
    op.create_index('idx_blog_posts_scheduled', 'blog_posts', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blog_posts_scheduled', table_name='blog_posts')
    op.drop_column('blog_posts', 'initial_likes')
    op.drop_column('blog_posts', 'initial_views')
    op.drop_column('blog_posts', 'scheduled_for')
    # ### end Alembic commands ###
