"""expand_payment_status_model_for_tinkoff

Revision ID: d365d57efcba
Revises: a1b2c3d4e5f6
Create Date: 2025-09-09 13:32:01.009501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd365d57efcba'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'widget_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    
    # Expand Payment model for complete Tinkoff integration
    op.add_column('payments', sa.Column('tinkoff_status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('card_mask', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove added Payment model columns
    op.drop_column('payments', 'payment_url')
    op.drop_column('payments', 'card_mask')
    op.drop_column('payments', 'error_message')
    op.drop_column('payments', 'error_code')
    op.drop_column('payments', 'customer_name')
    op.drop_column('payments', 'customer_phone')
    op.drop_column('payments', 'customer_email')
    op.drop_column('payments', 'tinkoff_status')
    
    op.alter_column('assistants', 'widget_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    # ### end Alembic commands ###
