"""add_keywords_to_blog_posts

Revision ID: d8ed002bc152
Revises: c87bcb311c52
Create Date: 2025-09-20 15:43:12.190536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ed002bc152'
down_revision: Union[str, Sequence[str], None] = 'c87bcb311c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'keywords')
    # ### end Alembic commands ###
