"""add google_id to user

Revision ID: f8195d7eed75
Revises: 2006abdd7c66
Create Date: 2025-06-18 15:42:53.700398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8195d7eed75'
down_revision: Union[str, Sequence[str], None] = '2006abdd7c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'last_name')
    op.drop_column('dialogs', 'first_name')
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    op.add_column('dialogs', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.add_column('dialogs', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
