name: RAD Agent Documentation Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'frontend/**' 
      - 'docs/**'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docs/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  documentation-lint:
    runs-on: ubuntu-latest
    name: Documentation Synchronization Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Нужно для сравнения изменений
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Setup Node.js  
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Install Node.js dependencies
        run: |
          cd backend/workers
          npm install
          
      - name: Run RAD Agent Lint (Warning Mode)
        run: |
          chmod +x scripts/agent-lint.sh
          FAIL_MODE=warn VERBOSE=true scripts/agent-lint.sh
          
      - name: Generate OpenAPI Schema
        run: |
          cd backend
          chmod +x scripts/gen_openapi.sh
          scripts/gen_openapi.sh
          
      - name: Check Documentation Currency
        run: |
          chmod +x scripts/check_docs_currency.py
          python3 scripts/check_docs_currency.py
          
      - name: Validate Critical Structure Changes
        run: |
          # Проверяем, были ли изменения в критических файлах структуры
          if git diff --name-only HEAD~1 | grep -E "(backend/workers|backend/api|backend/services)" > /dev/null; then
            echo "🔄 Обнаружены изменения в структуре - требуется проверка документации"
            
            # Жесткая проверка при структурных изменениях  
            FAIL_MODE=fail VERBOSE=true scripts/agent-lint.sh
          else
            echo "✅ Структурные изменения не обнаружены"
          fi
          
      - name: Archive documentation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation-check-results
          path: |
            docs/api/openapi.json
            scripts/check_docs_currency.py
            
  future-hard-gate:
    runs-on: ubuntu-latest
    name: Future Hard Gate (Currently Disabled)
    if: false  # Включится через 2-3 дня после внедрения
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd backend  
          pip install -r requirements.txt
          
      - name: Run RAD Agent Lint (Strict Mode)
        run: |
          chmod +x scripts/agent-lint.sh
          FAIL_MODE=fail VERBOSE=true scripts/agent-lint.sh
          
      - name: Validate OpenAPI Schema
        run: |
          # Генерируем свежую схему и сравниваем с зафиксированной
          cd backend
          chmod +x scripts/gen_openapi.sh
          scripts/gen_openapi.sh
          
          if ! cmp -s ../docs/api/openapi.json openapi_generated.json; then
            echo "❌ OpenAPI схема устарела! Требуется обновление:"
            echo "Запустите: cd backend && scripts/gen_openapi.sh && cp openapi_generated.json ../docs/api/openapi.json"
            exit 1
          fi
          
      - name: Validate Documentation Completeness
        run: |
          # Проверяем, что все API эндпоинты задокументированы
          python3 scripts/extract_all_endpoints.py > endpoints_actual.json
          
          # Сравниваем с задокументированными эндпоинтами
          if ! python3 -c "
          import json
          with open('endpoints_actual.json') as f: actual = set(json.load(f))
          with open('docs/api/endpoints.md') as f: documented = len([l for l in f if l.strip().startswith('###')])
          if len(actual) > documented * 1.2:  # Позволяем 20% расхождение
              print(f'❌ Найдено {len(actual)} эндпоинтов, но задокументировано только ~{documented}')
              exit(1)
          print(f'✅ Покрытие документацией: ~{documented}/{len(actual)} эндпоинтов')
          "; then
            exit 1
          fi